sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  global:
    - AFTER_SCRIPT='./build_script.sh'
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros/main CATKIN_CONFIG="-DCMAKE_BUILD_TYPE=Release"
    - ROS_DISTRO="kinetic" ROS_REPO=ros/main CATKIN_CONFIG="-DCMAKE_BUILD_TYPE=Release"

install:
  git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  source .ci_config/travis.sh
